### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RachaelBooth** [rikvandenberg/AzureFunctions.Extensions.DependencyInjection#1]
This seems like it could be useful to a lot of people, but there isn't a license included, which I think means it defaults to not being usable (although by github's terms I think we could fork it and use the fork).

Could you add a license of some kind, please?

**Comment by rikvandenberg** [comment]
Hi @RachaelBooth 

I'll just add an default MIT license. 
But I just have one question since this small library is just a adoption of an adoption of another library, should I include that specific license as well?

See mentioned commit.

Kind Regards,

Rik

**Comment by RachaelBooth** [comment]
Probably - I have to confess I am not an expert.

Thanks,
Rachael
