### ISSUE TITLE
Update to latest versions of WebJobs packages

### ISSUE THREAD

**Issue by gdodd1977** [rikvandenberg/AzureFunctions.Extensions.DependencyInjection#2]
Hi. Do you think you could update to the latest WebJobs packages so that this is compatible with Microsoft.Net.Sdk.Functions 1.0.13?

**Comment by rikvandenberg** [comment]
@gdodd1977 What kind of target framework are you using? I'm gonna assume you ran into the following issue when upgrading Microsoft.NET.Sdk.Functions to 1.0.12 or beyond.

![image](https://user-images.githubusercontent.com/397160/40411645-45f1d5c0-5e71-11e8-8b99-cb4aace12a57.png)

I've updated version `1.1.3` to depend upon 2.2.0 for net461 and  net471. The NuGet package should be indexed within the hour

**Comment by gdodd1977** [comment]
I'm on 461. 

Yep. That's the one!

Great. Thanks!
